site_name: Sara Willis

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - toc.integrate
  palette:
    primary: custom
    accent: custom


plugins:
  - blog
  - search

nav:
  - Home: index.md
  - CV: cv/index.md
  - Blog: 
    - blog/index.md

markdown_extensions:
  - tables
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: material/linkedin
      link: https://www.linkedin.com/in/saramariewillis/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-1605-6426
    - icon: fontawesome/brands/github
      link: https://github.com/SaraMWillis
  status:
    new: Recently added
  template: index.html
extra_css:
  - assets/stylesheets/extra.css
  